spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.yml
github:
  apiKey: ""
  baseApiUrl: "https://api.github.com"
  #  Must include organization if one exists
  teams:
    - "CenturyLinkCloud/advanced-storage"
  ignoredRepos:
    - ""
